export const SAVE_INITIAL_DATA_TO_STORE='SAVE_INITIAL_DATA_TO_STORE';
export const LOADING_START='LOADING_START';
export const LOADING_END='LOADING_END';
export const SET_OPTION_VALUE='SET_OPTION_VALUE';
export const CHANGE_PROGRESS='CHANGE_PROGRESS';




